apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: meals-calendar-ingress
spec:
  rules:
  - http:
      paths:
      - path: /meals-calendar/api/
        backend:
          serviceName: meals-calendar-deployment-svc
          servicePort: 8080
      - path: /meals-calendar/
        backend:
          serviceName: meals-calendar-ui-deployment-svc
          servicePort: 80
