apiVersion: v1
kind: ConfigMap
metadata:
  name: meals-calendar-config
  namespace: default
data:
  DB_URL: DB_URL_VALUE_HERE
  DB_USER: DB_USER_VALUE_HERE
  DB_PASS: DB_PASS_VALUE_HERE
  GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID_VALUE_HERE
  GOOGLE_CLIENT_SECRET: GOOGLE_CLIENT_SECRET_VALUE_HERE
  TOKEN_SECRET: TOKEN_SECRET_VALUE_HERE
